// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type UserCard struct {
	Name string `json:"name"`
	Num  int    `json:"num"`
}

type UserCardInput struct {
	Name string `json:"name"`
	Num  int    `json:"num"`
}
