// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BeginSessionInput struct {
	Begin   bool   `json:"begin"`
	Session string `json:"session"`
}

type EndSessionInput struct {
	End     bool   `json:"end"`
	Session string `json:"session"`
}

type Mutation struct {
}

type Query struct {
}

type Subscription struct {
}

type UserCard struct {
	Name            string `json:"name"`
	Num             int    `json:"num"`
	PollresultReady bool   `json:"pollresultReady"`
}

type UserCardInput struct {
	Session string `json:"session"`
	Name    string `json:"name"`
	Num     int    `json:"num"`
}
